### ISSUE TITLE
Xiaomi Mijia LYWSD02MMC Digital Hygrometer

### ISSUE THREAD

**Issue by jumping2000** [hobbypunk90/mithermometer#3]
do you plan to support the new Xiaomi Mijia LYWSD02MMC Digital Hygrometer?

**Comment by mateuszdrab** [comment]
Adding myself to this question, along with LYWSD03MMC. 

I currently have one of those for testing and I'd like to deploy more. 

I believe the code needed can be borrowed from https://github.com/custom-components/sensor.mitemp_bt/issues/7

This is a Home Assistant custom component which extracts the values all the Xiaomi sensors, the issue is, my HASS instance is hosted in docker, far from where the Bluetooth devices are.
